// <auto-generated />
namespace UniversityMgtSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class studentupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201207281027049_studentupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
